from __future__ import annotations

from datetime import timedelta
import os

DB_PATH = os.getenv("SFTS_DB_PATH", "sfts.db")

PASSWORD_MIN_LENGTH = 12
PASSWORD_REQUIRE_UPPER = True
PASSWORD_REQUIRE_LOWER = True
PASSWORD_REQUIRE_DIGIT = True
PASSWORD_REQUIRE_SYMBOL = True

PASSWORD_HASH_ITERATIONS = 100_000
PBKDF2_ITERATIONS = 100_000

ADMIN_USERNAME = os.getenv("SFTS_ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.getenv("SFTS_ADMIN_PASSWORD", "Admin!123456")

SESSION_TTL = timedelta(minutes=15)
SESSION_SLIDING_TTL = timedelta(minutes=15)

MAX_FILE_SIZE_BYTES = 100 * 1024 * 1024
CHUNK_SIZE = 64 * 1024

NONCE_CACHE_SIZE = 1000
NONCE_TTL = timedelta(minutes=10)

TIMESTAMP_SKEW_SECONDS = 300

HMAC_KEY_SIZE = 32

LOG_LEVEL = "INFO"

REQUEST_WINDOW_SECONDS = int(os.getenv("SFTS_REQUEST_WINDOW_SECONDS", "60"))
DDOS_SUSPECT_REQUESTS_PER_WINDOW = int(
	os.getenv("SFTS_DDOS_SUSPECT_REQUESTS_PER_WINDOW", "30")
)
DDOS_CRITICAL_REQUESTS_PER_WINDOW = int(
	os.getenv("SFTS_DDOS_CRITICAL_REQUESTS_PER_WINDOW", "60")
)
FREQUENCY_LOOKBACK_MINUTES = int(os.getenv("SFTS_FREQUENCY_LOOKBACK_MINUTES", "60"))
SECURITY_EVENTS_LIMIT = int(os.getenv("SFTS_SECURITY_EVENTS_LIMIT", "20"))
DDOS_BLOCK_DURATION_MINUTES = int(os.getenv("SFTS_DDOS_BLOCK_DURATION_MINUTES", "15"))

PROGRESSIVE_BLOCK_WINDOWS_MINUTES = os.getenv(
	"SFTS_PROGRESSIVE_BLOCK_WINDOWS_MINUTES", "5,15,60"
)
MFA_ISSUER = os.getenv("SFTS_MFA_ISSUER", "SFTS Secure")
MFA_TIME_STEP_SECONDS = int(os.getenv("SFTS_MFA_TIME_STEP_SECONDS", "30"))
MFA_ALLOWED_DRIFT_STEPS = int(os.getenv("SFTS_MFA_ALLOWED_DRIFT_STEPS", "1"))
MFA_BACKUP_CODES_COUNT = int(os.getenv("SFTS_MFA_BACKUP_CODES_COUNT", "8"))

MULTIPART_MAX_CHUNKS = int(os.getenv("SFTS_MULTIPART_MAX_CHUNKS", "1000"))
MULTIPART_CHUNK_SIZE = int(os.getenv("SFTS_MULTIPART_CHUNK_SIZE", str(1024 * 1024)))

WORKER_BATCH_SIZE = int(os.getenv("SFTS_WORKER_BATCH_SIZE", "25"))

DEFAULT_TRANSFER_TTL_HOURS = int(os.getenv("SFTS_DEFAULT_TRANSFER_TTL_HOURS", "24"))
ALLOWED_TRANSFER_TTL_HOURS = os.getenv("SFTS_ALLOWED_TRANSFER_TTL_HOURS", "1,24,168,720")

ENABLE_COMPRESSION_DEFAULT = os.getenv("SFTS_ENABLE_COMPRESSION_DEFAULT", "1") == "1"

DEFAULT_DAILY_QUOTA_BYTES = int(os.getenv("SFTS_DEFAULT_DAILY_QUOTA_BYTES", str(2 * 1024 * 1024 * 1024)))
DEFAULT_MONTHLY_QUOTA_BYTES = int(os.getenv("SFTS_DEFAULT_MONTHLY_QUOTA_BYTES", str(20 * 1024 * 1024 * 1024)))
DEFAULT_STORAGE_QUOTA_BYTES = int(os.getenv("SFTS_DEFAULT_STORAGE_QUOTA_BYTES", str(10 * 1024 * 1024 * 1024)))

MAX_BATCH_FILES = int(os.getenv("SFTS_MAX_BATCH_FILES", "50"))
MAX_SHARE_LINK_DOWNLOADS = int(os.getenv("SFTS_MAX_SHARE_LINK_DOWNLOADS", "10"))

EVENT_STREAM_POLL_SECONDS = float(os.getenv("SFTS_EVENT_STREAM_POLL_SECONDS", "2"))
SESSION_WARNING_SECONDS = int(os.getenv("SFTS_SESSION_WARNING_SECONDS", "120"))

SMTP_HOST = os.getenv("SFTS_SMTP_HOST", "")
SMTP_PORT = int(os.getenv("SFTS_SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SFTS_SMTP_USERNAME", "")
SMTP_PASSWORD = os.getenv("SFTS_SMTP_PASSWORD", "")
SMTP_FROM = os.getenv("SFTS_SMTP_FROM", "no-reply@sfts.local")
SMTP_USE_TLS = os.getenv("SFTS_SMTP_USE_TLS", "1") == "1"

BACKUP_DIR = os.getenv("SFTS_BACKUP_DIR", "backups")
BACKUP_INTERVAL_HOURS = int(os.getenv("SFTS_BACKUP_INTERVAL_HOURS", "24"))
